// Generated by CoffeeScript 1.8.0
(function() {
  var data, filters;

  data = {
    todos: [
      {
        title: 'first title',
        completed: false
      }, {
        title: 'second title',
        completed: true
      }
    ]
  };

  filters = {
    'filter-all': function(todo) {
      return true;
    },
    'filter-active': function(todo) {
      return !todo.completed;
    },
    'filter-completed': function(todo) {
      return todo.completed;
    }
  };

  $(function() {
    review.view('.todoapp', {
      active_filter: 'filter-all',
      events: {
        'keydown #new-todo': function(e) {
          if (e.which === 13) {
            data.todos.unshift({
              title: e.target.value,
              completed: false
            });
            return e.target.value = '';
          }
        },
        'click #filters': function(e) {
          return this.active_filter = e.target.className;
        },
        'change #toggle-all': function() {
          var all_checked, todo, _i, _len, _ref, _results;
          all_checked = this.scope('n-completed');
          _ref = data.todos;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            todo = _ref[_i];
            _results.push(todo.completed = !all_checked);
          }
          return _results;
        },
        'click #clear-completed': function() {
          return data.todos = data.todos.filter(function(item) {
            return !item.completed;
          });
        }
      },
      'n-completed': function() {
        return data.todos.filter(function(item) {
          return item.completed;
        }).length;
      },
      'n-left': function() {
        return data.todos.length - this.scope('n-completed');
      },
      afterSync: function(data) {
        this.$.find('#filters *').removeClass('selected');
        return this.$.find('.' + this.active_filter).addClass('selected');
      },
      onredraw: function() {
        return this.syncRoot(data);
      }
    });
    review.view('.todo', {
      events: {
        'change .toggle[type="checkbox"]': function(e) {
          this.item.completed = e.target.checked;
          return true;
        },
        'dblclick .view label': function() {
          this.parent().editing_todo = this.item;
          return this.defer((function(_this) {
            return function() {
              return $('[type="text"]:visible').focus();
            };
          })(this));
        },
        'blur [type="text"]': function(e) {
          this.item.title = e.target.value;
          return this.stopEditing();
        },
        'keydown [type="text"]': function(e) {
          if (e.which === 13) {
            this.stopEditing();
          }
          if (e.which === 27) {
            return this.stopEditing();
          } else {
            return false;
          }
        },
        'click .destroy': function(e) {
          return data.todos = data.todos.filter((function(_this) {
            return function(item) {
              return item !== _this.item;
            };
          })(this));
        }
      },
      stopEditing: function() {
        this.parent().editing_todo = null;
        return this.$.removeClass('editing');
      },
      afterSync: function(todo) {
        this.$.toggleClass('editing', this.parent().editing_todo === todo);
        this.$.toggleClass('completed', todo.completed);
        return this.$.toggleClass('hidden', !filters[this.parent().active_filter](todo));
      },
      onredraw: function() {
        return this.parent().redraw();
      }
    });
    return review.init($(".todoapp").get(0), data);
  });

}).call(this);

//# sourceMappingURL=todos.js.map
